# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friends.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 591)
        MainWindow.setStyleSheet("")
        self.IRFTool = QtWidgets.QWidget(MainWindow)
        self.IRFTool.setObjectName("IRFTool")
        self.friendsBg = QtWidgets.QFrame(self.IRFTool)
        self.friendsBg.setGeometry(QtCore.QRect(0, 0, 721, 591))
        self.friendsBg.setStyleSheet("background-color: rgb(46, 51, 72);")
        self.friendsBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friendsBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friendsBg.setObjectName("friendsBg")
        self.friendsManagerFrame = QtWidgets.QFrame(self.friendsBg)
        self.friendsManagerFrame.setGeometry(QtCore.QRect(15, 40, 291, 501))
        self.friendsManagerFrame.setStyleSheet("\n"
"border-radius: 8px;\n"
"background-color: rgba(19, 28, 53, 200);")
        self.friendsManagerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friendsManagerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friendsManagerFrame.setObjectName("friendsManagerFrame")
        self.refreshFriendsBtn = QtWidgets.QPushButton(self.friendsManagerFrame)
        self.refreshFriendsBtn.setGeometry(QtCore.QRect(80, 450, 131, 41))
        self.refreshFriendsBtn.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.refreshFriendsBtn.setObjectName("refreshFriendsBtn")
        self.topBarFriends = QtWidgets.QFrame(self.friendsManagerFrame)
        self.topBarFriends.setGeometry(QtCore.QRect(0, 0, 291, 21))
        self.topBarFriends.setStyleSheet("background-color: rgb(31, 34, 49);\n"
"background-color: rgb(18, 26, 45);\n"
"border-radius: 10px;")
        self.topBarFriends.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBarFriends.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBarFriends.setObjectName("topBarFriends")
        self.inviFrameFriends = QtWidgets.QFrame(self.topBarFriends)
        self.inviFrameFriends.setGeometry(QtCore.QRect(0, 9, 21, 71))
        self.inviFrameFriends.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inviFrameFriends.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inviFrameFriends.setObjectName("inviFrameFriends")
        self.inviFrameFriends2 = QtWidgets.QFrame(self.topBarFriends)
        self.inviFrameFriends2.setGeometry(QtCore.QRect(275, 10, 31, 80))
        self.inviFrameFriends2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inviFrameFriends2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inviFrameFriends2.setObjectName("inviFrameFriends2")
        self.friendManagerLabel = QtWidgets.QLabel(self.topBarFriends)
        self.friendManagerLabel.setGeometry(QtCore.QRect(20, 0, 251, 21))
        self.friendManagerLabel.setStyleSheet("font: 87 9pt \"Segoe UI Black\";\n"
"\n"
"color: rgb(28, 146, 214);")
        self.friendManagerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.friendManagerLabel.setObjectName("friendManagerLabel")
        self.friendList = QtWidgets.QListWidget(self.friendsManagerFrame)
        self.friendList.setGeometry(QtCore.QRect(15, 30, 261, 401))
        self.friendList.setStyleSheet("background-color: rgba(18, 26, 45, 190);\n"
"font: 87 9pt \"Segoe UI Black\";\n"
"border-radius: 0px;")
        self.friendList.setObjectName("friendList")
        self.friendRequestsLabel = QtWidgets.QLabel(self.friendsManagerFrame)
        self.friendRequestsLabel.setGeometry(QtCore.QRect(0, 430, 291, 16))
        self.friendRequestsLabel.setStyleSheet("font: 87 8pt \"Segoe UI Black\";\n"
"background-color: rgb(25, 33, 58);\n"
"color: rgb(28, 146, 214);\n"
"")
        self.friendRequestsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.friendRequestsLabel.setObjectName("friendRequestsLabel")
        self.frame = QtWidgets.QFrame(self.friendsBg)
        self.frame.setGeometry(QtCore.QRect(320, 140, 191, 261))
        self.frame.setStyleSheet("background-color: rgb(19, 28, 53);\n"
"border-radius: 10px;\n"
"font: 87 9pt \"Segoe UI Black\";\n"
"\n"
"color: rgb(28, 146, 214);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.acceptAllFriendsBtn = QtWidgets.QPushButton(self.frame)
        self.acceptAllFriendsBtn.setGeometry(QtCore.QRect(50, 80, 101, 31))
        self.acceptAllFriendsBtn.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.acceptAllFriendsBtn.setObjectName("acceptAllFriendsBtn")
        self.declineAllFriendsBtn = QtWidgets.QPushButton(self.frame)
        self.declineAllFriendsBtn.setGeometry(QtCore.QRect(50, 150, 101, 31))
        self.declineAllFriendsBtn.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.declineAllFriendsBtn.setObjectName("declineAllFriendsBtn")
        self.removeAllFriendsBtn = QtWidgets.QPushButton(self.frame)
        self.removeAllFriendsBtn.setGeometry(QtCore.QRect(49, 215, 101, 31))
        self.removeAllFriendsBtn.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.removeAllFriendsBtn.setObjectName("removeAllFriendsBtn")
        self.acceptAllFriendsLabel = QtWidgets.QLabel(self.frame)
        self.acceptAllFriendsLabel.setGeometry(QtCore.QRect(0, 50, 191, 20))
        self.acceptAllFriendsLabel.setStyleSheet("font: 87 9pt \"Segoe UI Black\";\n"
"\n"
"color: rgb(28, 146, 214);")
        self.acceptAllFriendsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.acceptAllFriendsLabel.setObjectName("acceptAllFriendsLabel")
        self.declineAllFriendsLabel = QtWidgets.QLabel(self.frame)
        self.declineAllFriendsLabel.setGeometry(QtCore.QRect(0, 120, 191, 20))
        self.declineAllFriendsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.declineAllFriendsLabel.setObjectName("declineAllFriendsLabel")
        self.removeAllFriendsLabel = QtWidgets.QLabel(self.frame)
        self.removeAllFriendsLabel.setGeometry(QtCore.QRect(0, 191, 191, 20))
        self.removeAllFriendsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.removeAllFriendsLabel.setObjectName("removeAllFriendsLabel")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, -1, 191, 31))
        self.label_4.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.friendSelected = QtWidgets.QFrame(self.friendsBg)
        self.friendSelected.setGeometry(QtCore.QRect(520, 140, 181, 261))
        self.friendSelected.setStyleSheet("background-color: rgb(19, 28, 53);\n"
"border-radius: 10px;\n"
"font: 87 9pt \"Segoe UI Black\";\n"
"\n"
"color: rgb(28, 146, 214);")
        self.friendSelected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friendSelected.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friendSelected.setObjectName("friendSelected")
        self.friendNameLabel = QtWidgets.QLabel(self.friendSelected)
        self.friendNameLabel.setGeometry(QtCore.QRect(0, -1, 181, 31))
        self.friendNameLabel.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.friendNameLabel.setText("")
        self.friendNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.friendNameLabel.setObjectName("friendNameLabel")
        self.pushButton = QtWidgets.QPushButton(self.friendSelected)
        self.pushButton.setGeometry(QtCore.QRect(40, 80, 101, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.friendSelected)
        self.pushButton_2.setGeometry(QtCore.QRect(39, 150, 101, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.banMessageBtn = QtWidgets.QPushButton(self.friendSelected)
        self.banMessageBtn.setGeometry(QtCore.QRect(39, 215, 101, 31))
        self.banMessageBtn.setStyleSheet("QPushButton {\n"
"    font: 87 9pt \"Arial Black\";\n"
"    color: rgb(28, 146, 214);\n"
"    background-color: rgb(16, 24, 45);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(17, 25, 47, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(16, 24, 45);\n"
"\n"
"\n"
"}")
        self.banMessageBtn.setObjectName("banMessageBtn")
        self.label = QtWidgets.QLabel(self.friendSelected)
        self.label.setGeometry(QtCore.QRect(0, 50, 191, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.friendSelected)
        self.label_2.setGeometry(QtCore.QRect(0, 120, 191, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.friendSelected)
        self.label_3.setGeometry(QtCore.QRect(0, 190, 191, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.IRFTool)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.refreshFriendsBtn.setText(_translate("MainWindow", "REFRESH"))
        self.friendManagerLabel.setText(_translate("MainWindow", "Friends Manager"))
        self.friendRequestsLabel.setText(_translate("MainWindow", "Friend Requests: 0"))
        self.acceptAllFriendsBtn.setText(_translate("MainWindow", "ACCEPT"))
        self.declineAllFriendsBtn.setText(_translate("MainWindow", "DECLINE"))
        self.removeAllFriendsBtn.setText(_translate("MainWindow", "REMOVE"))
        self.acceptAllFriendsLabel.setText(_translate("MainWindow", "Accept All Friend Requests"))
        self.declineAllFriendsLabel.setText(_translate("MainWindow", "Decline All Friend Requests"))
        self.removeAllFriendsLabel.setText(_translate("MainWindow", "Remove All Friends"))
        self.label_4.setText(_translate("MainWindow", "Features"))
        self.pushButton.setText(_translate("MainWindow", "COPY"))
        self.pushButton_2.setText(_translate("MainWindow", "COPY"))
        self.banMessageBtn.setText(_translate("MainWindow", "SEND"))
        self.label.setText(_translate("MainWindow", "Copy Icon"))
        self.label_2.setText(_translate("MainWindow", "Copy Status"))
        self.label_3.setText(_translate("MainWindow", "Fake Ban Message"))
